spring:
  datasource: 
    url: jdbc:postgresql://localhost:5432/hotel
    username: postgres
    password: minhthichlag
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      fail-on-empty-beans: false